// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return const FirebaseOptions(
        apiKey: 'AIzaSyD5FIodSb7ZNqUTfjLHJzPGt_aknxJUtpQ',
        appId: '1:879267203995:web:REPLACE_WITH_YOUR_WEB_APP_ID',
        messagingSenderId: '879267203995',
        projectId: 'speshway-3d072',
        authDomain: 'speshway-3d072.firebaseapp.com',
        storageBucket: 'speshway-3d072.firebasestorage.app',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5FIodSb7ZNqUTfjLHJzPGt_aknxJUtpQ',
    appId: '1:879267203995:android:5085f16431f6791236ef3e',
    messagingSenderId: '879267203995',
    projectId: 'speshway-3d072',
    storageBucket: 'speshway-3d072.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCXnjFQQGnFihTiqeUSLG8_HvmWWWHG7k',
    appId: '1:879267203995:ios:aa261b9f42734e3736ef3e',
    messagingSenderId: '879267203995',
    projectId: 'speshway-3d072',
    storageBucket: 'speshway-3d072.firebasestorage.app',
    iosBundleId: 'com.speshway.staff',
  );
}
