// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      // This app doesn't actually build for web — this branch is
      // unreachable in practice, but kept pointed at the real client
      // project (carzzi-a8bf4, same as android/ios below) rather than the
      // old "speshway-3d072" project, and reuses the android app's
      // credentials as a placeholder since no distinct web app has been
      // registered under carzzi-a8bf4.
      return const FirebaseOptions(
        apiKey: 'AIzaSyA09SBVbovG5LbRqP77Tg7pf4bzWYXRP3g',
        appId:
            '1:295776629143:android:d58ef4c4d150a41f9914d2', // Using android one for now as placeholder
        messagingSenderId: '295776629143',
        projectId: 'carzzi-a8bf4',
        authDomain: 'carzzi-a8bf4.firebaseapp.com',
        storageBucket: 'carzzi-a8bf4.firebasestorage.app',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA09SBVbovG5LbRqP77Tg7pf4bzWYXRP3g',
    appId: '1:295776629143:android:d58ef4c4d150a41f9914d2',
    messagingSenderId: '295776629143',
    projectId: 'carzzi-a8bf4',
    storageBucket: 'carzzi-a8bf4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGyyQwWj7ir3qZDKz9jXgyoDy1Mt3VGdI',
    appId: '1:295776629143:ios:97b1f88afbf5c7539914d2',
    messagingSenderId: '295776629143',
    projectId: 'carzzi-a8bf4',
    storageBucket: 'carzzi-a8bf4.firebasestorage.app',
    iosBundleId: 'com.carzzi.staff',
  );
}
