// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      // TODO: Add your web configuration here
      return const FirebaseOptions(
        apiKey: 'AIzaSyD5FIodSb7ZNqUTfjLHJzPGt_aknxJUtpQ',
        appId:
            '1:879267203995:web:8f4d521df251253536ef3e', // Using android one for now as placeholder
        messagingSenderId: '879267203995',
        projectId: 'speshway-3d072',
        authDomain: 'speshway-3d072.firebaseapp.com',
        storageBucket: 'speshway-3d072.firebasestorage.app',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA09SBVbovG5LbRqP77Tg7pf4bzWYXRP3g',
    appId: '1:295776629143:android:6648b48402b49c839914d2',
    messagingSenderId: '295776629143',
    projectId: 'carzzi-a8bf4',
    storageBucket: 'carzzi-a8bf4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGyyQwWj7ir3qZDKz9jXgyoDy1Mt3VGdI',
    appId: '1:295776629143:ios:19e270e65cf8a66a9914d2',
    messagingSenderId: '295776629143',
    projectId: 'carzzi-a8bf4',
    storageBucket: 'carzzi-a8bf4.firebasestorage.app',
    iosBundleId: 'com.carzzi.user',
  );
}
